name: Creating Atmosphere
favicon: null
layout_spectrum: 0.3457236415706575
typography_spectrum: 0.51635732781142
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.21674037305638194
  lightness: 0.5579777515958995
  saturation: 0.8122558225877583
  rhythmicContrast: 0.22806132794357836
purpose: []
